### ISSUE TITLE
영어버전 출시(기능 다른 것은 없고 메세지만 해석)

### ISSUE THREAD

**Issue by minebuilder050** [monun/speculation#10]
이렇게 완성된 게임이 한국어에만 한정되어있는 것이 아쉽습니다.  외국인 친구들에게도 소개하고 싶지만 언어의 장벽의 문제로 하기 어렵습니다. 영어버전이 가능한가요?

**Comment by ghost** [comment]
개인적으로 포크해서 영어버전 나중에 제작해볼 생각은 있습니당

**Comment by ghost** [comment]
영어버전은... 뭐 오픈소스여서 라이선스 지키면 직접 제작이나 다른 사람이 제작이 가능 할 것 같습니다. :)
이슈 닫아주세요.
