### ISSUE TITLE
부동산 투기 서버 리소스팩 무한로딩

### ISSUE THREAD

**Issue by khyunnn** [monun/speculation#11]
부동산 투기 서버에 들어갔는데 리소스팩이 무한로딩되면서 pc 드라이브 용량이 점점 줄어들더니 20기가까지 잡아먹길래 결국 마크를 강제종료했습니다. (종료하면 용량은 다시 돌아옵니다). 마인크래프트 서버 리소스팩 내부 폴더에는 정상적으로 다운되었으나 적용이 안되는 문제가 있는거 같아요. 마크 자체 문제인가 해서 리소스팩을 요구하는 다른 서버에 들어가봤더니 정상적으로 작동하길래 혹시나 리소스팩이 적용될때 오류가 있을수도 있다는 생각이 들어서 글을 씁니다
지금도 해보고 있는데 1시간째임 
![화면 캡처 2021-12-25 031017](https://user-images.githubusercontent.com/96631875/147368273-d57b0bb0-a19e-4d26-9e87-fcc70994a17f.png)

옵티파인 켯을때도 껏을때도 똑같이 이럽니다. 개인적으로 만들어서 사용하는 리소스팩도 전부 해제하고 다른 모드도 없이 순수 마인크래프트만 이용했을때도 같은 결과가 나왔습니다.

**Comment by wavgado** [comment]
**마인크래프트를 삭제했다가 다시 설치해보세요**

**Comment by ghost** [comment]
개인 문제이신 것 같습니다.

확인 결과 리소스팩은 한번만 다운로드 되었고 이외에는 문제가 없었습니다.

환경 또는 컴퓨터도 차이 없습니다. 윈도우, 맥, 리눅스 전부다 작동되고 일반 가정 컴퓨터든 서버 컴퓨터든 피방 컴퓨터든(네 됩니다...) 정상 작동되었습니다.

개인 설정을 다시 한번 확인해보시길 바랍니다.

**Comment by ghost** [comment]
해결이 되지 않으실 경우 #13 번 Pull Request가 받아 진 뒤 플러그인을 다시 다운로드 하여 `/speculation resourcepack` 명령을 실행해보세요. 그래도 작동이 되지 않을 경우 수동으로 리소스팩을 적용하시면 될 것 같습니다.

`.minecraft/resourcepacks`폴더내에 리소스팩 파일 저장 -> 마인크래프트를 실행해 설정에서 리소스팩 파일 불러옴 -> 서버 접속 이전에 "서버 수정"을 눌러 리소스팩 옵션을 사용하지 않음으로 변경 -> 서버 리소스팩 강제화가 아니기에 진행 될 것으로 보임

앞서 말씀드렸지만 **#13  번 Pull Request가 받아지지 않는 한** 개인 설정 확인 의외의 의미는 없을 것으로 보입니다.

**Comment by ghost** [comment]
#13 번 Pull Request가 받아졌습니다! 최신 빌드로 플레이하시면됩니다. 이슈 닫아주세요.

**Comment by khyunnn** [comment]
> 부동산 투기 서버에 들어갔는데 리소스팩이 무한로딩되면서 pc 드라이브 용량이 점점 줄어들더니 20기가까지 잡아먹길래 결국 마크를 강제종료했습니다. (종료하면 용량은 다시 돌아옵니다). 마인크래프트 서버 리소스팩 내부 폴더에는 정상적으로 다운되었으나 적용이 안되는 문제가 있는거 같아요. 마크 자체 문제인가 해서 리소스팩을 요구하는 다른 서버에 들어가봤더니 정상적으로 작동하길래 혹시나 리소스팩이 적용될때 오류가 있을수도 있다는 생각이 들어서 글을 씁니다 지금도 해보고 있는데 1시간째임 ![화면 캡처 2021-12-25 031017](https://user-images.githubusercontent.com/96631875/147368273-d57b0bb0-a19e-4d26-9e87-fcc70994a17f.png)
> 
> 옵티파인 켯을때도 껏을때도 똑같이 이럽니다. 개인적으로 만들어서 사용하는 리소스팩도 전부 해제하고 다른 모드도 없이 순수 마인크래프트만 이용했을때도 같은 결과가 나왔습니다.
