### ISSUE TITLE
방송에서 사용이 가능한 것인지

### ISSUE THREAD

**Issue by X-PeterBlood** [monun/speculation#12]
출처를 표기하고 방송에서도 사용이 가능한 컨텐츠인가요?

아무래도 각별님의 시청자를 위해 시청자와 같이 제작한 컨텐츠라 방송 사용이 불가능하다고 생각이 들지만

혹시나 하는 마음으로 각별님의 생각 또는 의견을 들어보고 싶습니다.

**Comment by monun** [comment]
'오픈소스'

**Comment by zlfn** [comment]
첨언하자면... GNU GPL 3.0 라이센스라 그 프로그램은 어떻게든 제한 없이 사용 가능합니다.
다만 소스 코드 수정하시고 공개하실때는 GPL 라이센스를 따라주셔야 하고요.
https://olis.or.kr/license/Detailselect.do?lId=1072

**Comment by concertypin** [comment]
이슈 닫아주세요
