### ISSUE TITLE
서버에 어떻게 들어가고 어떻게 서버를 여나요?

### ISSUE THREAD

**Issue by Jang-Yoon** [monun/speculation#14]
서버를 여는거는 처음부터 못해서 궁금하고 서버를 들어가지도 못해서.... bat열고 아무키나 입력하라고 해서 입력하면  명령 프롬프트가 나가지고 마크를 들어가서 싱글플레이에 들어가도 서버가 없고 멀티플레이에서도 없고 localhost를 쳐도 못들어가는데 들어가고 서버를 여는방법 좀 알려주세요

**Comment by zlfn** [comment]
bat파일 실행했을 때 정확히 어떤 메시지가 나왔는지 알려주셔야 도와드릴 수 있습니다.

**Comment by zlfn** [comment]
서버 여는법 자체는 Readme에 자세하게 설명되어 있습니다.

**Comment by Jang-Yoon** [comment]
서버  여는법 자체가  있는 Readme을 똑같이 따라해도 서버가 안열리고
C:\Users\82106\Desktop\부루마불>java -jar -Xmx4G -Xms4G paper-1.17.1-401.jar --nogui
Minecraft 1.17 requires running the server with Java 16 or above. Download Java 16 (or above) from https://adoptopenjdk.net/

C:\Users\82106\Desktop\부루마불>pause
계속하려면 아무 키나 누르십시오 . . .
라고 뜹니다

**Comment by zlfn** [comment]
마크 1.17부터는 자바 16이상만 서버 열리게 바뀌어서 자바 16 다운받으셔야 해요.

https://www.youtube.com/watch?v=k1wjjoMx_eU

대충 이거대로 해보시고 해결 되셨으면 이슈 닫아주세요.

**Comment by Jang-Yoon** [comment]
혹시 서버에 들어가지긴했는데 리소스팩이 적용이 안됐는데 리소스팩은 어디서 다운받나요? 그리고 친구랑 하고싶은데 어떻게 하는지 모르겠어요ㅠ

**Comment by zlfn** [comment]
리소스팩은 게임 시작하면 자동으로 적용이 되고 친구랑 하는 법은 하마치나 포트포워딩 인터넷 검색하시면 잘 나올겁니다.
