### ISSUE TITLE
리소스팩 적용안됨 (with 수동설치)

### ISSUE THREAD

**Issue by changwook987** [monun/speculation#21]
마인크래프트 서버 리소스팩 폴더 비우기 등 여러 짓을 해본 결과
서버에서 리소스팩을 다운받는 것 까지는 문제가 없는 것 같아서
리소스팩을 수동으로 설치 해봤는데 리소스팩 자체가 적용이 안되는 것 같습니다.

**Comment by changwook987** [comment]
혹시 리소스팩을 적용시키기 위해서 모드가 필요한가요?
(옵티파인이나 패브릭?)

**Comment by zlfn** [comment]
아니요 게임 시작하면 자동으로 적용될텐데요…?

**Comment by changwook987** [comment]
어...?

https://user-images.githubusercontent.com/80932551/154846324-5a98d6a6-f381-4094-8c9e-e2a240c384b9.mp4

안될 이유가 없는데...

**Comment by ghost** [comment]
추후 확인해볼게요 문제없을텐데 뭐지

**Comment by ghost** [comment]
![Screenshot](https://user-images.githubusercontent.com/36562850/180633875-37054176-af01-4ba8-b3c7-cc122cfc7de1.png)

한참 예전의 이슈이긴 합니다만 진짜 안될 이유가 없습니다
(혹 문제가 이미 해결되었다면 이슈 종료를 부탁드려요)
