### ISSUE TITLE
횡성 팀 색

### ISSUE THREAD

**Issue by sgkill6** [monun/speculation#76]
소 뒤에 원만 색이 달라야하는데 뿔색은 왜 달라지죠 각별님이 뿔로 바꾸신건가요

**Comment by monun** [comment]
어 이거 이제봤네...ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

근데 인식하기 쉬워서 굳이 바꾸진 않을듯합니다

**Comment by sgkill6** [comment]
알겠습니다
