### ISSUE TITLE
국세청 클릭범위 제안

### ISSUE THREAD

**Issue by zlfn** [monun/speculation#9]
국세청에서 돈뜯길때 국세청 땅을 클릭해야 하는데, 보통 플레이어는 주사위를 던지느라 좀 멀리 가있습니다.
그러니까 국세청에 걸리면 국세청에 빠르게 달려가서 내 돈이 뜯기는걸 막아야 한다는 것이죠.
**그냥 아무데나 클릭해도 되게 하면 안될까요?**

**Comment by monun** [comment]
'의도'

**Comment by zlfn** [comment]
아하...
![image](https://user-images.githubusercontent.com/33383685/147100105-af3ad0e6-4f49-409e-b81b-3b771fd50cd0.png)

**Comment by ghost** [comment]
왜그랬어요
