### ISSUE TITLE
저 제출안되거나 오류가 있었나요??

### ISSUE THREAD

**Issue by ham4286** [monun/speculation#92]
포탈이랑 춘천 만들었었는데 아예 어디서도 볼수가 없어서요...

**Comment by ham4286** [comment]
아님 퀄리티가 너무 낮나요??

**Comment by spaceguy4** [comment]
저두여 저도 안동을 만들어서 보냈지만, 어디서도 볼 수 없었습니다.

**Comment by obinox** [comment]
각님이 PR을 아직 수락하지 않았으니 당연히 안보이죠

**Comment by ham4286** [comment]
아 그렇군요! 대답 감사합니다.
